language: python

# http://docs.travis-ci.com/user/ci-environment/#CI-environment-OS
before_install: travis_retry ./bootstrap/ubuntu.sh

install: "travis_retry pip install tox coveralls"
script: "travis_retry tox"

after_success: '[ "$TOXENV" == "cover" ] && coveralls'

# using separate envs with different TOXENVs creates 4x1 Travis build
# matrix, which allows us to clearly distinguish which component under
# test has failed
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=lint
  - TOXENV=cover

notifications:
  email: false
  irc: "chat.freenode.net#letsencrypt"
