language: python

before_install: >
  travis_retry sudo apt-get install python python-setuptools
  python-virtualenv python-dev gcc swig dialog libaugeas0 libssl-dev

install: "travis_retry pip install tox coveralls"
script: "travis_retry tox"

after_success: coveralls

# using separate envs with different TOXENVs creates 4x1 Travis build
# matrix, which allows us to clearly distinguish which component under
# test has failed
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=lint
  - TOXENV=cover

notifications:
  email: false
  irc: "chat.freenode.net#letsencrypt"
