language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python python-setuptools python-virtualenv python-dev gcc swig dialog libaugeas0 libssl-dev
install:
  - pip install -e .[testing]
  - pip install tox
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=lint
script:
  - tox -e $TOX_ENV
